fix Android manifest for Expo SDK 51
I got this error during prebuild with @expo/cli@canary:
✖ Prebuild failed
Error: [android.manifest]: withAndroidManifestBaseMod: A runtime version is set in your AndroidManifest.xml, but is missing from your app.json/app.config.js. Please either set runtimeVersion in your app.json/app.config.js or remove expo.modules.updates.EXPO_RUNTIME_VERSION from your AndroidManifest.xml.

I think I just need to mirror the commit here:
https://github.com/expo/expo/commit/dd8f245bfb048ed385cee09673339769bd2dd343